services:
  web:
    image: nginx
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./var/www:/var/www
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=mylocaldomain.ch
      - NGINX_PORT=80